name: 'BenchmarkExplorer CI'
description: 'Run Julia benchmarks and save results in BenchmarkExplorer format with persistent history'
author: 'Yaroslav Kachur'

branding:
  icon: 'activity'
  color: 'purple'

inputs:
  benchmark_script:
    description: 'Path to the Julia file that defines SUITE (default: src/benchmarks_trixi.jl)'
    required: false
    default: 'src/benchmarks_trixi.jl'

  benchmark_project:
    description: 'Path to Julia project directory for benchmark (if different from main). Leave empty to use main project.'
    required: false
    default: ''

  data_dir:
    description: 'Path to data directory (default: data)'
    required: false
    default: 'data'

  group_name:
    description: 'Benchmark group name (default: trixi)'
    required: false
    default: 'trixi'

  julia_version:
    description: 'Julia version to use (default: "1.11")'
    required: false
    default: '1.11'

  persist_to_branch:
    description: 'Branch to persist history data (default: gh-pages). Set to empty to disable persistence.'
    required: false
    default: 'gh-pages'

  persist_path:
    description: 'Path within persist branch to store history (default: benchmarks/)'
    required: false
    default: 'benchmarks/'

  github_token:
    description: 'GitHub token for pushing results'
    required: true

outputs:
  data_dir:
    description: 'Path to the data directory with benchmark results'
    value: ${{ inputs.data_dir }}

  num_benchmarks:
    description: 'Number of benchmarks executed'
    value: ${{ steps.run_benchmarks.outputs.num_benchmarks }}

runs:
  using: 'composite'
  steps:
    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ inputs.julia_version }}

    - name: Cache Julia packages
      uses: actions/cache@v4
      with:
        path: ~/.julia
        key: julia-${{ runner.os }}-${{ inputs.julia_version }}-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
        restore-keys: |
          julia-${{ runner.os }}-${{ inputs.julia_version }}-

    - name: Fetch existing data from persist branch
      if: inputs.persist_to_branch != ''
      shell: bash
      run: |
        git fetch origin ${{ inputs.persist_to_branch }} || true
        mkdir -p ${{ inputs.data_dir }}
        git show origin/${{ inputs.persist_to_branch }}:${{ inputs.persist_path }}index.json > ${{ inputs.data_dir }}/index.json 2>/dev/null || true
        git show origin/${{ inputs.persist_to_branch }}:${{ inputs.persist_path }}latest_100.json > ${{ inputs.data_dir }}/latest_100.json 2>/dev/null || true
        mkdir -p ${{ inputs.data_dir }}/by_group/${{ inputs.group_name }}
        git archive origin/${{ inputs.persist_to_branch }} ${{ inputs.persist_path }}by_group/${{ inputs.group_name }} | tar -x -C ${{ inputs.data_dir }} 2>/dev/null || true

    - name: Run benchmarks
      id: run_benchmarks
      shell: bash
      env:
        BENCHMARK_GROUP: ${{ inputs.group_name }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        julia ${{ github.action_path }}/ci/run_benchmarks.jl "${{ inputs.data_dir }}" "${{ inputs.group_name }}"

    - name: Publish results to persist branch
      if: inputs.persist_to_branch != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        cp -r ${{ inputs.data_dir }} /tmp/data_update
        cp -r ${{ github.action_path }}/ci /tmp/ci_scripts

        git fetch origin ${{ inputs.persist_to_branch }} || true
        git clean -fdx

        if git rev-parse --verify origin/${{ inputs.persist_to_branch }} >/dev/null 2>&1; then
          git checkout -B ${{ inputs.persist_to_branch }} origin/${{ inputs.persist_to_branch }}
        else
          git checkout --orphan ${{ inputs.persist_to_branch }}
          git rm -rf . || true
        fi

        mkdir -p ${{ inputs.persist_path }}
        cp -r /tmp/data_update/* ${{ inputs.persist_path }}

        julia /tmp/ci_scripts/generate_index_page.jl ${{ inputs.persist_path }} ${{ inputs.persist_path }}index.html \
          "${{ github.server_url }}/${{ github.repository }}" "${{ github.sha }}"

        julia /tmp/ci_scripts/generate_static_page.jl ${{ inputs.persist_path }} \
          ${{ inputs.persist_path }}${{ inputs.group_name }}.html ${{ inputs.group_name }} \
          "${{ github.server_url }}/${{ github.repository }}" "${{ github.sha }}"

        git add -A
        git commit -m "Update benchmarks: ${{ inputs.group_name }} @ ${{ github.sha }}" || echo "No changes"
        git push origin ${{ inputs.persist_to_branch }}

        git checkout -f ${{ github.sha }}

    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-data-${{ inputs.group_name }}
        path: ${{ inputs.data_dir }}
        retention-days: 30
