name: 'BenchmarkExplorer CI'
description: 'Run Julia benchmarks and save results in BenchmarkExplorer format with persistent history'
author: 'Yaroslav Kachur'

branding:
  icon: 'activity'
  color: 'purple'

inputs:
  benchmark_script:
    description: 'Path to the Julia file that defines SUITE. Leave empty for built-in groups (trixi, enzyme, nanosoldier).'
    required: false
    default: ''

  benchmark_project:
    description: 'Value passed to the --project flag. The default value is the repository root: "@."'
    required: false
    default: '@.'

  data_dir:
    description: 'Path to data directory (default: data)'
    required: false
    default: 'data'

  group_name:
    description: 'Benchmark group name (default: trixi)'
    required: false
    default: 'trixi'

  julia_version:
    description: 'Julia version to use (default: "1.11")'
    required: false
    default: '1.11'

  persist_to_branch:
    description: 'Branch to persist history data (default: gh-pages). Set to empty to disable persistence.'
    required: false
    default: 'gh-pages'

  persist_path:
    description: 'Path within persist branch to store history (default: benchmarks/)'
    required: false
    default: 'benchmarks/'

  github_token:
    description: 'GitHub token for pushing results'
    required: true

outputs:
  data_dir:
    description: 'Path to the data directory with benchmark results'
    value: ${{ inputs.data_dir }}

  num_benchmarks:
    description: 'Number of benchmarks executed'
    value: ${{ steps.run_benchmarks.outputs.num_benchmarks }}

runs:
  using: 'composite'
  steps:
    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ inputs.julia_version }}

    - name: Cache Julia packages
      uses: actions/cache@v4
      with:
        path: ~/.julia
        key: julia-${{ runner.os }}-${{ inputs.julia_version }}-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
        restore-keys: |
          julia-${{ runner.os }}-${{ inputs.julia_version }}-

    - name: Fetch existing data from persist branch
      if: inputs.persist_to_branch != ''
      shell: bash
      run: |
        git fetch origin ${{ inputs.persist_to_branch }} || true
        mkdir -p ${{ inputs.data_dir }}
        git show origin/${{ inputs.persist_to_branch }}:${{ inputs.persist_path }}index.json > ${{ inputs.data_dir }}/index.json 2>/dev/null || true
        git show origin/${{ inputs.persist_to_branch }}:${{ inputs.persist_path }}latest_100.json > ${{ inputs.data_dir }}/latest_100.json 2>/dev/null || true
        mkdir -p ${{ inputs.data_dir }}/by_group/${{ inputs.group_name }}
        git archive origin/${{ inputs.persist_to_branch }} ${{ inputs.persist_path }}by_group/${{ inputs.group_name }} | tar -x -C ${{ inputs.data_dir }} 2>/dev/null || true
        mkdir -p ${{ inputs.data_dir }}/by_hash
        git archive origin/${{ inputs.persist_to_branch }} ${{ inputs.persist_path }}by_hash | tar -x -C ${{ inputs.data_dir }} 2>/dev/null || true

    - name: Instantiate user project
      if: inputs.group_name != 'nanosoldier'
      run: |
        import Pkg
        Pkg.resolve()
        Pkg.instantiate()
      shell: julia --color=yes --project=${{ inputs.benchmark_project }} {0}

    - name: Run benchmarks
      id: run_benchmarks
      shell: bash
      env:
        BENCHMARK_GROUP: ${{ inputs.group_name }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        julia --color=yes --project=${{ inputs.benchmark_project }} \
          ${{ github.action_path }}/ci/run_benchmarks.jl \
          "${{ inputs.data_dir }}" "${{ inputs.group_name }}" "${{ inputs.benchmark_script }}"

    - name: Install dependencies for HTML generation
      if: inputs.persist_to_branch != ''
      shell: bash
      run: |
        julia --project=${{ github.action_path }} -e 'using Pkg; Pkg.instantiate()'

    - name: Generate HTML pages
      if: inputs.persist_to_branch != ''
      shell: bash
      run: |
        mkdir -p /tmp/benchmark_html

        julia --project=${{ github.action_path }} ${{ github.action_path }}/ci/generate_index_page.jl \
          ${{ inputs.data_dir }} /tmp/benchmark_html/index.html \
          "${{ github.server_url }}/${{ github.repository }}" "${{ github.sha }}"

        julia --project=${{ github.action_path }} -e '
          include(ARGS[1])
          using JSON
          latest = JSON.parsefile(joinpath(ARGS[2], "latest_100.json"))
          for group in keys(get(latest, "groups", Dict()))
            println("Generating page for: ", group)
            generate_static_page_plotly(ARGS[2], joinpath(ARGS[3], group * ".html"), group, ARGS[4], ARGS[5])
          end
        ' -- "${{ github.action_path }}/ci/generate_static_page_plotly.jl" \
          "${{ inputs.data_dir }}" "/tmp/benchmark_html" \
          "${{ github.server_url }}/${{ github.repository }}" "${{ github.sha }}"

        julia --project=${{ github.action_path }} -e 'include("${{ github.action_path }}/src/HistoryManager.jl"); using .HistoryManager; generate_all_runs_index("${{ inputs.data_dir }}")'

    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-data-${{ inputs.group_name }}
        path: ${{ inputs.data_dir }}
        retention-days: 30

    - name: Publish results to persist branch
      if: inputs.persist_to_branch != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        cp -r ${{ inputs.data_dir }} /tmp/data_update

        git fetch origin ${{ inputs.persist_to_branch }} || true
        git clean -fdx

        if git rev-parse --verify origin/${{ inputs.persist_to_branch }} >/dev/null 2>&1; then
          git checkout -B ${{ inputs.persist_to_branch }} origin/${{ inputs.persist_to_branch }}
        else
          git checkout --orphan ${{ inputs.persist_to_branch }}
          git rm -rf . || true
        fi

        if [ -n "${{ inputs.persist_path }}" ]; then
          mkdir -p ${{ inputs.persist_path }}
          cp -r /tmp/data_update/* ${{ inputs.persist_path }}
          cp /tmp/benchmark_html/*.html ${{ inputs.persist_path }}
        else
          cp -r /tmp/data_update/* .
          cp /tmp/benchmark_html/*.html .
        fi

        git add -A
        git commit -m "Update benchmarks: ${{ inputs.group_name }} @ ${{ github.sha }}" || echo "No changes"
        git push origin ${{ inputs.persist_to_branch }}

        git checkout -f ${{ github.sha }}
