name: Deploy Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run Benchmarks]
    types:
      - completed


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: gh-pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - run: |
          curl -sS -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq .
        env:
          GITHUB_TOKEN: ${{ github.token }}
        name: Rate limits github.token
      - run: |
          curl -sS -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Rate limits GITHUB_TOKEN
      - id: deploy
        uses: actions/deploy-pages@v4
